name: ci
on:
  schedule:
    - cron:  '30 4 * * 3' # Run on every Wednesday
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docker-compose.yml'
    branches:
      - 'master'

jobs:
  bake-latest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            dcagatay/ubuntu-dind:latest
            dcagatay/ubuntu-dind:22.04
          build-args: |
            UBUNTU_TAG=22.04

  bake-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "20.04"
          - "18.04"
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            dcagatay/ubuntu-dind:${{matrix.version}}
          build-args: |
            UBUNTU_TAG=${{matrix.version}}
