name: ci
on:
  schedule:
    - cron:  '30 4 * * 3' # Run on every Wednesday
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docker-compose.yml'
    branches:
      - 'master'

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version from Dockerfile
        id: version_provider
        run: |
          VERSION=$(grep 'ARG UBUNTU_TAG' Dockerfile | awk -F= '{print $2}')
          echo "BASE_CONTAINER_VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: debug
        run: |
          echo "::debug:: ${{ env.BASE_CONTAINER_VERSION }}"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            dcagatay/ubuntu-dind:latest
          tags: |
            dcagatay/ubuntu-dind:latest
            dcagatay/ubuntu-dind:${{ env.BASE_CONTAINER_VERSION }}
          build-args: |
            UBUNTU_TAG=22.04

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: dcagatay/ubuntu-dind

  build-others:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "20.04"
          # - "18.04"
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            dcagatay/ubuntu-dind:${{matrix.version}}
          build-args: |
            UBUNTU_TAG=${{matrix.version}}
